/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'khn3193' at '5/6/17 8:49 PM' with Gradle 2.13
 *
 * @author khn3193, @date 5/6/17 8:49 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
